"""由 transcript.json 生成 AI 修正版字幕对照稿 transcript.corrected.txt。

原则（用户约定）：逐段保留讲师原始字词与顺序，不合并、不改写为书面语；
仅做两类修改——(1) ASR 错词替换（MAP）；(2) 口癖清理（纯语气词整段删除、
句尾语气词剥离、单字口吃叠词折叠）。MAP 可按视频扩充。

用法: python make_corrected.py <video_id> [<video_id> ...] | --all
"""
import argparse
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ASR 错词 -> 正确词（按长度降序应用，避免子串误伤）
MAP = {
    "深圳市软件工程": "生成式软件工程",
    "英拉SEMBLY": "内联汇编",
    "英外SAMBLY": "内联汇编",
    "inline sembly": "内联汇编",
    "英line sembly": "内联汇编",
    "chain of salt": "chain of thought",
    "chal thought": "chain of thought",
    "chef s": "chain of thought",
    "chap out": "chain of thought",
    "chp out": "chain of thought",
    "CHAPSP": "chain of thought",
    "test time skilling": "test-time scaling",
    "试time skilling": "test-time scaling",
    "cloud opo4.5": "Claude Opus 4.5",
    "MANUEL伯纳姆": "Manuel Blum",
    "hugin face": "Hugging Face",
    "open street map": "OpenStreetMap",
    "home brew": "Homebrew",
    "exterminate js": "xterm.js",
    "xterm js": "xterm.js",
    "deep sv4flash": "DeepSeek",
    "deep sick with the flash": "DeepSeek",
    "deep pick": "DeepSeek",
    "deep chick": "DeepSeek",
    "D4C": "DeepSeek",
    "DIVSK": "DeepSeek",
    "KIMIK3": "Kimi K3",
    "GPT5.6": "GPT-5.6",
    "GBT5.6": "GPT-5.6",
    "GPP5.6": "GPT-5.6",
    "GP5.6": "GPT-5.6",
    "GPT56": "GPT-5.6",
    "cheat gp d": "ChatGPT",
    "CHEGBT": "ChatGPT",
    "拆GBT": "ChatGPT",
    "拆GPT": "ChatGPT",
    "拆GPA": "ChatGPT",
    "terry machine": "Turing machine",
    "church tcs": "Church-Turing 论题",
    "habalton pass": "哈密顿路径",
    "ham alton": "哈密顿",
    "three reset": "3-SAT",
    "justin time": "just-in-time",
    "include pass": "include path",
    "yo mode": "YOLO mode",
    "low list": "allowlist",
    "AI slap": "AI slop",
    "passer": "parser",
    "sober": "solver",
    "agents点MD": "agents.md",
    "AGENTS点MD": "agents.md",
    "agent4点MD": "agents.md",
    "agency md": "agents.md",
    "H4点MD": "agents.md",
    "卢卡": "LUCA",
    "杠I": "-I",
    "在ID里": "在 IDE 里",
    "ID里面": "IDE 里面",
    "ID的": "IDE 的",
    "GBT": "ChatGPT",
    "威尔法尔": "verifier",
    "威尔法": "verifier",
    "VERIFILE": "verifier",
    "VERIFI": "verifier",
    "WIFI": "verifier",
    "linux": "Linux",
    # ── BV1kybV6DE47 软件仓库管理（本地 large-v3 ASR 稿）──
    "GP16": "GPT-6",
    "GP6": "GPT-6",
    "GP5.6": "GPT-5.6",
    "GP5": "GPT-5",
    "义父楼": "逸夫楼",
    "光山玩具": "光栅玩具",
    "光山尺": "光栅尺",
    "巨深赛道": "具身赛道",
    "操系统": "操作系统",
    "外部": "外包",
    "webcoding": "vibe coding",
    "web coding": "vibe coding",
    "webcode": "vibe code",
    "Vichy Studio": "Visual Studio",
    "hello.ce": "hello.c",
    "hello.ca": "hello.c",
    "git积交": "git 提交",
    "Basic Practice": "best practice",
    "confessional commits": "Conventional Commits",
    "chat gpg": "ChatGPT",
    "fixed井三": "fixes #3",
    "井三": "#3",
    ".ds-store": ".DS_Store",
    ".dstor": ".DS_Store",
    "DS Store": ".DS_Store",
    "command and fund": "command not found",
    "GH或者GLab": "gh 或者 glab",
    "GLab": "glab",
    "一个go说": "一个 goal 说",
    "汉诺坦": "汉诺塔",
    "双机": "双击",
    "灵光一线": "灵光一现",
    "巨声无比": "巨大无比",
    "bysect": "bisect",
    "by set": "bisect",
    "Community History": "commit history",
    "computer object": "commit object",
    "committed object": "commit object",
    "committed message": "commit message",
    "CommitMessage": "commit message",
    "hide是指向": "HEAD 是指向",
    "ZXY的循环": "X、Y、Z 的循环",
    "就可以出科技": "就可以出效果",
    "都是AIS了": "都是 AI slop 了",
    "一个ATI": "一个 API",
    "cs6ea": "cs61a",
    "learn git branching.js.org": "learngitbranching.js.org",
    "Bitkeeper": "BitKeeper",
    "ProGit": "Pro Git",
    "Git Unity": "git init",
    "git unity": "git init",
    "off by onein strlencheck": "off-by-one in strlen check",
    "state of art": "state of the art",
    "Virtual Implement就": "Virtual Implementation 就",
    "NEO VM": "Neovim",
    "MPM": "npm",
    "cherrypick": "cherry-pick",
    "Implantation": "Implementation",
    "Intent and Spat": "Intent 和 Spec、",
    "Information的空间": "Implementation 的空间",
    "Redmi": "README",
    "Readme": "README",
    "AI Stop": "AI Slop",
    "deep-seek": "DeepSeek",
    "全大学会": "全大写会",
    "前移默化": "潜移默化",
    "不定的变好": "不停地变好",
    "省上要的": "省 token 的",
    "快招": "快照",
    "测试用力": "测试用例",
    "报打好": "包打好",
    "或者流打": "或者流水线",
    "CICD": "CI/CD",
    "precommitted hook": "pre-commit hook",
    "interment": "int main(void)",
    "intimate void": "int main(void)",
    "监控号": "尖括号",
    "叫hours": "叫 ours",
    "可以reveal": "可以 revert",
    "agency.md": "AGENTS.md",
    "agent.cmd": "AGENTS.md",
    "考案神": "convention",
    "超系统课": "计算机系统课",
    # ── BV1Q6en6NEUo 软件仓库管理(2)（B 站 ai-zh 字幕）──
    "web code": "vibe code",
    "A证": "agent", "A政": "agent", "A震": "agent",
    "交流坑": "焦油坑",
    "AI is lap": "AI slop", "a s lap": "AI slop", "AISLOFT": "AI slop",
    "slot out": "slop", "生成SP2": "生成 slop",
    "get it work tree": "git worktree",
    "get it by sec": "git bisect", "get it blame": "git blame",
    "get it report": "git repo", "get it ripple": "git repo",
    "Get it": "git", "get it": "git", "gate": "git",
    "点get": ".git", "ripple": "repo",
    "rapport点BB": "repo.db", "report点dB": "repo.db",
    "GGT": "jj", "GG词": "jj", "GG子": "jj", "JUJS": "jj", "JUSS": "jj",
    "句句词": "Jujutsu", "JJS": "jj",
    "瑞贝斯": "rebase",
    "REBASESTHSTH": "rebase stash",
    "get sth": "git stash", "STH": "stash", "statch": "stash", "STATCH": "stash", "SSTACK": "stash stack",
    "t max": "tmux", "tm session": "tmux session", "体Mark": "tmux",
    "work tree": "worktree", "WALKTHROUGH": "worktree", "WORKTI": "worktree",
    "WORKT吗": "worktree 上吗", "walk around": "workaround",
    "deep pick": "DeepSeek", "DPCV4flash": "DeepSeek V4 Flash", "desk v4": "DeepSeek V4",
    "cloud code": "Claude Code", "Cloud code": "Claude Code",
    "oor leaf": "Overleaf",
    "subversion": "subagent",
    "哈洛塔": "汉诺塔",
    "variable product": "viable product", "PARAA": "paradigm",
    "S mail": "email", "SMAIL": "email",
    "L1号": "一卡通", "一号": "一卡通",
    "skin log": "scaling law",
    "播骷髅": "workflow",
    "adversary lock": "advisory lock",
    "C口查询": "SQL 查询",
    "主威镇": "主 agent", "主位制": "主座位",
    "traction的": "transaction 的", "traction sq说": "transaction 说",
    "BT": "abort", "OLBOT": "abort",
    "singles ready": "single-threaded", "single studi": "single-threaded", "single spread": "single-threaded",
    "a j mod": "agent mode",
    "spring shots": "screenshots",
    "SPICATION": "specification",
    "COMMERCISCIENCE": "computer science", "converter science": "computer science",
    "TRACABILITY": "traceability", "suffer trace ability": "software traceability",
    "seating error": "staging area",
    "persistent data加structure": "persistent data structure",
    "SPN": "SVN",
    "PARADIM": "paradigm",
    "git点NHU点E点点CN": "git.nju.edu.cn",
    "three bet": "rebase",
    "computing m": "contributing.md", "contributing点MD": "contributing.md",
    "现行历史": "线性历史",
    "read me点MD": "README.md", "read me": "README",
    "C加加": "C++",
    "点text文件": ".tex 文件",
    "pickle playground": "playground",
    "idol了": "edit 了",
    "GTT起": "GPT 也", "原原话": "原话",
    "SISTANT点dB": "assistant.db",
    "da base": "database",
    "VTREE": "worktrees", "GDIR": "gitdir:",
    "STANFORDMIT": "Stanford、MIT",
    "GITHUB论接": "GitHub 链接",
    "福岛工厂": "富士康",
    "AI戳我上大学": "AI 替我上大学",
    "GALGAME": "GalGame",
    "PREPRINT": "preprint",
    # —— 通用模型/术语 ASR 修正 ——
    "G p t5.6": "GPT-5.6",
    "GPU5.2": "GPT-5.2",
    "gm5.3": "GPT-5.3",
    "JM5.3": "GPT-5.3",
    "GM5.3": "GPT-5.3",
    "gm或者DP": "Gemini 或者 DeepSeek",
    "g p t": "GPT",
    "cloud fable": "Claude",
    "open cloud": "Claude",
    "open cow": "Claude",
    "AMOS": "Reminders",
    "ARMUS": "Reminders",
    "DBP": "DeepSeek",
    "DVPC": "DeepSeek",
    "deep pk": "DeepSeek",
    "deep sk v4flash": "DeepSeek V4 Flash",
    "deep sk v4pro": "DeepSeek V4 Pro",
    "deep sick with flash": "DeepSeek V4 Flash",
    "deep with flash": "DeepSeek V4 Flash",
    "DP g vs flash": "DeepSeek V4 Flash",
    "deep sk": "DeepSeek",
    "d pk": "DeepSeek",
    "vision flash": "V4 Flash",
    "v4flash": "V4 Flash",
    "v4pro": "V4 Pro",
    "大圆模型": "大语言模型",
    "圆的模型": "大语言模型",
    "NEWM": "Neovim",
    "new wave": "Neovim",
    "LISCODE": "LeetCode",
    "content test code": "content is code",
    "everything is cold": "everything is code",
    "龙葵艾泽": "long horizon",
    "龙华ERROM": "long horizon",
    "龙华森": "long horizon",
    "lower ion": "long horizon",
    "GPT-5.64号给的": "GPT-5.6 给的",
    "5.6售的": "5.6",
    "GCLVM": "GLM",
    "千万3点八": "千问 3.8",
    "欧拉码": "Ollama",
    "evil算": "calc 算",
    "PRLM": "pre-LLM",
    "prim m": "pre-LLM",
    "梁文谷": "梁文锋",
    "梁文峰": "梁文锋",
    "一号点NG优点一点CN": "ehall.nju.edu.cn",
    "一号点N99.16CN": "ehall.nju.edu.cn",
    "一号点N": "ehall.nju.edu.cn",
    "99.16CN": "",
    "一号的研究": "ehall 的研究",
    "channel少女": "助手",
    "pental design flame": "fundamental design flaw",
    "rethink u": "rethink it",
    "build exce": "build Excel",
    "AI is log": "AI slop",
    "AI s log": "AI slop",
    "AI AI s law": "AI slop",
    "AI s law": "AI slop",
    "rider AI is love NO": "write AI is love",
    "react": "ReAct",
    "conversion": "conversation",
    "work body": "workflow",
    "想模管理豆包": "豆包",
    "Macbook cup": "MacBook Cup",
    "所以质朴": "所以 GPT",
    "GPD4": "GPT-4",
    "GP4": "GPT-4",
    "oppo token": "output token",
    "color code": "Codex",
    "后勤连线人": "long horizon",
    "四超过": "超过",
    # —— 软件仓库管理(2) BV1Q6en6NEUo 术语 ——
    "一号点N": "ehall.nju.edu.cn",
    "一号": "ehall",
    "get it": "git",
    "Get it": "git",
    "比gate要好": "比 git 要好",
    "JJS": "jj",
    "JUSS": "jj",
    "GG子": "jj",
    "GGT": "jj",
    "句句词": "jj",
    "t max": "tmux",
    "T max": "tmux",
    "体Mark": "tmux",
    "SMAIL": "email",
    "VIVO": "view",
    "TRACABILITY": "traceability",
    "AISLOFT": "AI slop",
    "a s lap": "AI slop",
    "斯拉夫克": "slop",
    "single spread": "single-threaded",
    "singles ready": "single-threaded",
    "single studi": "single-threaded",
    "cloud code": "Claude Code",
    "Cloud code": "Claude Code",
    "让cloud": "让 Claude",
    "codex": "Codex",
    "report点dB": "repo.db",
    "SISTANT点dB": "assistant.db",
    "adversary lock": "advisory lock",
    "OLBOT": "abort",
    "STATCH": "stash",
    "STH": "stash",
    "A证": "agent",
    "A震": "agent",
    "A镇": "agent",
    "A正": "agent",
    "跟AJ": "跟 agent",
    "GTT": "GPT",
    "GP的原话": "GPT 的原话",
    "overleaf": "Overleaf",
    "oor leaf": "Overleaf",
    "persd": "per second",
    "PARAA": "paradigm",
    "PARADIM": "paradigm",
    "contributing点MD": "CONTRIBUTING.md",
    "read me": "README",
    "点get": ".git",
    "点text": ".tex",
    "瑞贝斯": "rebase",
    "traction": "transaction",
    "DPC": "DeepSeek",
    "DeepSeekV4": "DeepSeek V4",
    "ripple": "repo",
    "rapport": "repo",
    "git report": "git repo",
    "report status": "repo status",
    "个report": "个 repo",
    "这个report": "这个 repo",
}
_MAP_ITEMS = sorted(MAP.items(), key=lambda kv: -len(kv[0]))

# 整段即为口癖 -> 删除该段
FILLER_ONLY = {"呃", "嗯", "啊", "哦", "啧", "哎", "哎呀", "哈哈", "哈哈哈", "嘿嘿",
               "对", "对吧", "对啊", "好啊", "好", "好的", "然后", "任何", "额",
               "anyway", "Anyway", "ANYWAY", "呃呃", "嗯嗯", "啊哈", "呜", "喂", "yes", "no"}

# 句尾口癖 -> 剥离
TAIL_FILLER = re.compile(r"(?:对吧|对不对|是吧|是不是|嘛|呀|哦|呃|嗯|哈哈|哈|啊|呢)+$")

# 单字口吃叠词折叠：我我我->我 等
STUTTER = re.compile(r"(我|你|他|它|就|是|有|去|来|啊|呃|嗯|对|但|那|这|也|都|还|又|再|很|太|会|要|想|说|看|做|搞|弄|写|读|问|答|学|教|玩|用|给|把|被|让|使|等)\1+")


def correct(text: str):
    for old, new in _MAP_ITEMS:
        if old in text:
            text = text.replace(old, new)
    text = text.replace("呃", "").replace("嗯", "")
    text = STUTTER.sub(r"\1", text)
    text = TAIL_FILLER.sub("", text).strip()
    return text


def main():
    ap = argparse.ArgumentParser(description="生成 AI 修正版字幕对照稿")
    ap.add_argument("video_id", nargs="*")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()
    ids = args.video_id or [d for d in sorted(os.listdir(os.path.join(BASE, "output")))
                            if os.path.isfile(os.path.join(BASE, "output", d, "transcript.json"))]
    for vid in ids:
        src = os.path.join(BASE, "output", vid, "transcript.json")
        segs = json.load(open(src, encoding="utf-8"))["segments"]
        out_lines, dropped, fixed = [], 0, 0
        for seg in segs:
            raw = seg["text"].strip()
            if raw in FILLER_ONLY:
                dropped += 1
                continue
            txt = correct(raw)
            if txt != raw:
                fixed += 1
            if not txt:
                dropped += 1
                continue
            h, m, s = seg["start"].split(":")
            mm = int(h) * 60 + int(m)
            out_lines.append(f"[{mm:02d}:{s}] {txt}")
        dst = os.path.join(BASE, "output", vid, "transcript.corrected.txt")
        with open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out_lines) + "\n")
        print(f"{vid}: {len(segs)} 段 -> {len(out_lines)} 行（修正 {fixed} 行，删除口癖段 {dropped}）")


if __name__ == "__main__":
    main()
